# IRT

## Item Response Theory

### CTT and IRT

**item response theory**

To support the development of instruments and measure characteristics in individuals, test theories have
been used to describe how inferences, predictions, or estimates of a particular characteristic, trait, or ability
of a person may be made from responses to items. Test theories such as classical test theory (CTT) and
item response theory (IRT) provide models for explaining test performance in relation to variables that are
assumed to influence behavior. They provide methods for selecting items, evaluating tests or scales,
obtaining scores, and quantifying sources of errors in the measurement process. 

Item response theory (IRT) is one of several test theories that may be applied to assessment data to describe
how estimates, inferences, and predictions of a particular characteristic, trait, or ability of a person may be
made from responses to test items (Lord & Novick, 1969). Test theories provide models for explaining test
performance in relation to variables that are presumed to influence item response. Furthermore, they
provide methods for obtaining scores and for quantifying errors in measurement. 

CTT is an intuitive model that relates observed scores to true scores plus errors in
measurement. Useful results from applications of CTT to assessment responses include estimation of item
characteristics (for example, item difficulty), observed score reliability, and quantifying error in
measurement (standard error of measurement – SEM). However, these and other results depend on the
group of examinees from which they are derived. 

IRT addresses shortcomings of CTT and also solves practical problems related to test development. 
Compared to CTT, which models responses at the test level, IRT models focus attention on the item level 
by modeling or predicting performance for individual items. If the model is appropriate, properties for items are independent of the specific group that is assessed (person-free measurement)



















